---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Kuniwak/vint
    rev: 9a239b20be279324ced3b34ed71f84a63edfd4fb
    hooks:
      - id: vint
        exclude: >
          (?x)^(
            vim/colors/.*\.vim
          )$
  - repo: local
    hooks:
      - id: luacheck
        name: Luacheck
        entry: luacheck
        args:
          - --globals
          - vim
          - --
        language: system
        types: [file, lua]
