---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Kuniwak/vint
    rev: v0.4a3
    hooks:
      - id: vint
        exclude: >
          (?x)^(
            vim/colors/.*\.vim
          )$
  - repo: https://github.com/johnnymorganz/stylua
    rev: v0.17.1
    hooks:
      - id: stylua-github
  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.1.0
    hooks:
      - id: luacheck
        args:
          - --globals
          - vim
          - --
  - repo: local
    hooks:
      - id: sort-json
        name: sort json files with jq
        language: script
        entry: ./scripts/sort-json.sh
        files: "(\\.json$|^neovim/packer_snapshots/)"
        types: [text]
