---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Kuniwak/vint
    rev: v0.4a3
    hooks:
      - id: vint
        exclude: >
          (?x)^(
            vim/colors/.*\.vim
          )$
  - repo: local
    hooks:
      - id: selene
        name: An opinionated Lua code linter
        entry: selene
        language: system
        types: [lua]
      - id: stylua
        name: An opinionated Lua code formatter
        entry: selene
        language: system
        types: [lua]
