---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Kuniwak/vint
    rev: v0.4a3
    hooks:
      - id: vint
        exclude: >
          (?x)^(
            vim/colors/.*\.vim
          )$
  - repo: local
    hooks:
      - id: luacheck
        name: Luacheck
        entry: luacheck
        args:
          - --globals
          - vim
          - --
        language: system
        types: [file, lua]
  - repo: https://github.com/johnnymorganz/stylua
    rev: v0.14.3
    hooks:
      - id: stylua-system
  - repo: local
    hooks:
      - id: sort-json
        name: sort json files with jq
        language: script
        entry: ./scripts/sort-json.sh
        files: "(\\.json$|^neovim/packer_snapshots/)"
