---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Kuniwak/vint
    rev: v0.4a3
    hooks:
      - id: vint
        exclude: >
          (?x)^(
            vim/colors/.*\.vim
          )$
  - repo: local
    hooks:
      - id: luacheck
        name: Luacheck
        entry: luacheck
        args:
          - --globals
          - vim
          - --
        language: system
        types: [file, lua]
  - repo: https://github.com/IamTheFij/StyLua
    rev: pre-commit-hook
    hooks:
      - id: stylua
        args: ["--indent-type", "Spaces"]
