local utils = require("utils")
utils.keymap_set("n", ">", function()
    require("quicker").expand({ before = 2, after = 2, add_to_existing = true })
end, { desc = "Expand quickfix context", buffer = true })
utils.keymap_set("n", "<", function()
    require("quicker").collapse()
end, { desc = "Collapse quickfix context", buffer = true })
utils.keymap_set("n", "<C-r>", function()
    require("quicker").refresh()
end, { desc = "Refresh quickfix context", buffer = true })
